#+title: « La Révolution russe, une histoire française »

Mardi 9 janvier 2018

Mardi d'*Acrimed* avec *Éric Aunoble*, auteur de /La Révolution russe, une histoire française/, à propos du traitement médiatique de la révolution de 1917 (à l'époque et aujourd'hui).

L'association *Acrimed* s'est déjà penchée à de nombreuses reprises sur la place et les usages de l'histoire dans les médias dominants, de son écriture sous forme de récit distrayant à son instrumentalisation politique, de la résurgence d'une histoire « identitaire » à la promotion des « historiens de garde ». Alors que le centième anniversaire de l'année 1917 en Russie s'achève, il nous a semblé particulièrement intéressant de revenir sur la médiatisation de cet épisode historique majeur, en la comparant avec les différentes lectures qu'il a suscitées au cours du siècle écoulé.

Dans son livre /La Révolution russe, une histoire française/, paru en 2016, *Éric Aunoble*, historien spécialiste de la révolution russe et enseignant à l'université de Genève, étudie à travers un vaste corpus de journaux, d'ouvrages politiques, historiques ou romanesques, la réception en France, de 1917 à aujourd'hui, de ces « jours qui ébranlèrent le monde ». Il fait le constat d'un retournement de la lecture des événements -- « de l'engouement au dénigrement et à l'effacement » -- en particulier depuis la fin de l'URSS. Un retournement qui se cristallise avec la publication du polémique Livre noir du communisme, en 1997.

Comment la révolution russe a-t-elle été traitée dans les médias français à l'époque et à l'occasion de son centenaire ? Pourquoi ? En quoi ce traitement nous éclaire-t-il, plus largement, le rapport de ces derniers avec la science historique et l'Histoire ? Pour débattre de ces questions, Éric Aunoble sera notre invité.


* « La Révolution russe, une histoire française »

En France, la révolution russe est devenue un repoussoir, le moment fondateur d'un totalitarisme aussi terrifiant que le nazisme. Elle n'est plus envisagée que sous l'angle de ses victimes, aussi bien dans le discours public que dans les manuels scolaires. Éric Aunoble retrace la réception de l'événement en France depuis 1917 - comment L'Humanité, aux mains des socialistes d'Union sacrée, vilipende la révolution bolchevique ; comment le Parti communiste, créé dans la foulée d'Octobre, impose une lecture de plus en plus stalinienne, se mariant après la Seconde Guerre mondiale avec le discours déterministe de l'Université. Ainsi sont étouffées les voix dissidentes, celles des premiers communistes français, familiers de Lénine et Trotsky. L'usage politique de 1917 se dessèche et Mai 68 ne voit réémerger que des clichés du bolchevisme (qui témoignent toutefois de l'importance de l'événement dans la culture populaire). Au long d'un siècle, la révolution russe a été lue en fonction du contexte politique français. Ainsi s'explique le retournement qui s'est joué, de l'engouement au dénigrement et à l'effacement d'aujourd'hui, quand triomphe le conservatisme et son rejet de toute « culture révolutionnaire ».

* Éric Aunoble

Éric Aunoble est historien et enseignant à l'université de Genève. 
Il est l'auteur de /«Le communisme tout de suite ! », le mouvement des Communes en Ukraine Soviétique (1919-1920)/, aux Nuits Rouges (2008). 

* Passages mentionnant l'Humanité

*Couverture de la Révolution russe dans la presse française de l'époque*

- 09'03" :: 2è problème: la France a un problème particulier avec la Russie tsariste. C'est quelque chose qui est apparu dans le grand public en 1923 quand l'Humanité -- l'organe de la section française du Parti Communiste -- publie une série d'articles sous le titre général « L'abominable vénalité de la Presse ».

  C'est un effet du choix politique qu'avaient fait les Bolchevik de mettre fin à la diplomatie secrète ; et en particulier Trotsky, devenu Commissaire du peuple aux affaires étrangères, avait commencé à publier tout ce qui était secret dans les archives du Ministère des Affaires étrangères tsariste. Et c'est comme ça qu'on avait découvert l'activité d'une officine dirigée par un dénommé Rafalovich, qui était en relation avec l'ambassade de Russie en France et le ministère des Affaires étrangères, et dont le rôle était de distribuer de l'argent pour qu'on dise du bien de la Russie en France.

  Sachant que l'enjeu n'était pas seulement un eujeu d'image mais très réel: la fin du XIXè siècle et le début du XXè, c'est l'époque des emprunts russes ; et donc l'enjeu de la bonne image de la Russie en France, c'est d'arriver à placer les emprunts russes auprès de la petite bourgeoisie française, qu'elle choisisse de mettre ses économies dans le développement de l'économie russe plutôt qu'ailleurs.

  D'après les documents publiés, Rafalovich a distribué entre 1900 et 1913 6,5 millions de francs pour soigner l'image de la Russie tsariste en France.

- 27'57" :: Autre cas intéressant: l'Humanité.

  Journal socialiste, mais journaliste d'union sacrée, jusqu'en novembre 17 (...)

  L'Humanité envoie un correspondant à Petrograd, précisément en octobre, i.e. 1,5 mois avant la prise du pouvoir par les Bolchevik. C'est un Russe: *Boris Krichewsky*, marxiste, et parmi les premiers militants marxistes russes, donc il a tout pour faire le job. Lui, ce qu'il voit en octobre, c'est des Apaches. Entre autre, ce qu'il décrit est tout à fait vrai, i.e. le pillage des caves à vin du Tsar, mais il le décrit abondamment et y voit la vérité du régime dans la saoulographie généralisée des gardes rouges, et en plus il qualifie les Bolchevik d'anarcho-léninistes...

  Tout s'explique quand on sait que Boris Krichewsky était en effet un des premiers marxistes russes, mais en même temps c'était un des premiers opposants à Lénine, et que, dès que Lénine avait commencé à proposer sa vision de la construction d'un parti révolutionnaire en Russie, Krichewsky avait été un de ses premiers oposants ; et donc il était en exil en France depuis les années 1904 ou 1905, était resté opposé à Lénine, et donc l'Humanité envoie un correspondant totalement opposé à ça.

  Sachant que, comme les équilibres de force à l'intérieur de la SFIO se modifie, le pauvre Krichewsky voit ses chroniques assez rapidement ne plus être publiées, parce qu'au sein de la SFIO la majorité union sacrée est affaiblie par la fin de l'union sacrée, et Krichewsky avec son côté anti-Bolchevik, apparaît comme trop droitier pour la nouvelle ligne majoritaire de l'Humanité


*Couverture médiatique de la Révolution russe en 2016-2017*

- 46'06" ::  L'Humanité a fait un numéro spécial au mois de juin. Il traduit assez bien l'embarras du Parti Communiste: il ont décidé de ne pas choisir, c'est-à-dire qu'on y trouve 2 personnes qui ont droit à un article (et ça a pu faire hurler dans les chaumières communistes et staliniennes): *Jean-Jacques Marie*, trotskyste (et je pense que chez certains anciens ça a pu faire jaser), mais aussi *Nicolas Werth*.

  Et là je dois avouer que Nicolas Werth dans l'Humanité, ça m'en a bouché un coin...

  J'ai eu l'occasion de participer à un certain nombre de tables rondes, beaucoup moins médiatiques, organisées par le PC en son siège, et en en discutant avec un des organisateurs, il disait qu'il n'y avait pas eu vraiment de choix de fait et que tout le monde avait fait un peu ce qu'il voulait dans son coin, y compris les débats auxquels j'ai participé montraient que tout le monde cherchait un peu un truc à se raccrocher, sans trop savoir à quoi
