#+title: « La Révolution russe, une histoire française »

Mardi 9 janvier 2018

Mardi d'*Acrimed* avec *Éric Aunoble*, auteur de /La Révolution russe, une histoire française/, à propos du traitement médiatique de la révolution de 1917 (à l'époque et aujourd'hui).

L'association *Acrimed* s'est déjà penchée à de nombreuses reprises sur la place et les usages de l'histoire dans les médias dominants, de son écriture sous forme de récit distrayant à son instrumentalisation politique, de la résurgence d'une histoire « identitaire » à la promotion des « historiens de garde ». Alors que le centième anniversaire de l'année 1917 en Russie s'achève, il nous a semblé particulièrement intéressant de revenir sur la médiatisation de cet épisode historique majeur, en la comparant avec les différentes lectures qu'il a suscitées au cours du siècle écoulé.

Dans son livre /La Révolution russe, une histoire française/, paru en 2016, *Éric Aunoble*, historien spécialiste de la révolution russe et enseignant à l'université de Genève, étudie à travers un vaste corpus de journaux, d'ouvrages politiques, historiques ou romanesques, la réception en France, de 1917 à aujourd'hui, de ces « jours qui ébranlèrent le monde ». Il fait le constat d'un retournement de la lecture des événements -- « de l'engouement au dénigrement et à l'effacement » -- en particulier depuis la fin de l'URSS. Un retournement qui se cristallise avec la publication du polémique Livre noir du communisme, en 1997.

Comment la révolution russe a-t-elle été traitée dans les médias français à l'époque et à l'occasion de son centenaire ? Pourquoi ? En quoi ce traitement nous éclaire-t-il, plus largement, le rapport de ces derniers avec la science historique et l'Histoire ? Pour débattre de ces questions, Éric Aunoble sera notre invité.


* « La Révolution russe, une histoire française »

En France, la révolution russe est devenue un repoussoir, le moment fondateur d'un totalitarisme aussi terrifiant que le nazisme. Elle n'est plus envisagée que sous l'angle de ses victimes, aussi bien dans le discours public que dans les manuels scolaires. Éric Aunoble retrace la réception de l'événement en France depuis 1917 - comment L'Humanité, aux mains des socialistes d'Union sacrée, vilipende la révolution bolchevique ; comment le Parti communiste, créé dans la foulée d'Octobre, impose une lecture de plus en plus stalinienne, se mariant après la Seconde Guerre mondiale avec le discours déterministe de l'Université. Ainsi sont étouffées les voix dissidentes, celles des premiers communistes français, familiers de Lénine et Trotsky. L'usage politique de 1917 se dessèche et Mai 68 ne voit réémerger que des clichés du bolchevisme (qui témoignent toutefois de l'importance de l'événement dans la culture populaire). Au long d'un siècle, la révolution russe a été lue en fonction du contexte politique français. Ainsi s'explique le retournement qui s'est joué, de l'engouement au dénigrement et à l'effacement d'aujourd'hui, quand triomphe le conservatisme et son rejet de toute « culture révolutionnaire ».

* Éric Aunoble

Éric Aunoble est historien et enseignant à l'université de Genève. 
Il est l'auteur de /«Le communisme tout de suite ! », le mouvement des Communes en Ukraine Soviétique (1919-1920)/, aux Nuits Rouges (2008). 
